# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
#Step 1: Formulate the Hypotheses
#Null Hypothesis HO: The mean HP of Dragon-type Pokémon is equal to the mean HP of Grass-type Pokémon.
# mu HP_dragon == mu HP_grass
# mu HP_dragon > mu HP_grass



#Alternative Hypothesis H1: The mean HP of Dragon-type Pokémon is greater than the mean HP of Grass-type Pokémon.


#Step 2: #significance level = 0.05

In [21]:
df_dragon = df[(df['Type 1'] == 'Dragon') | (df['Type 2'] == 'Dragon')]['HP']
df_grass = df[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Grass')]['HP']

In [18]:
df_dragon = df_dragon.dropna()
df_dragon.isnull().sum()

Name          0
Type 1        0
Type 2        0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [19]:
df_grass = df_grass.dropna()

df_grass.isnull().sum()

Name          0
Type 1        0
Type 2        0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64

In [24]:
st.ttest_ind(df_dragon, df_grass, equal_var=False)

TtestResult(statistic=4.097528915272702, pvalue=0.00010181538122353851, df=77.58086781513519)

In [ ]:
# p_value is lower then significance level = 0.05 so we regect HO hypotesis, so HP diferent for Pokemons Dragon and Grass

In [28]:
df_dragon = df[(df['Type 1'] == 'Dragon') | (df['Type 2'] == 'Dragon')]
df_grass = df[(df['Type 1'] == 'Grass') | (df['Type 2'] == 'Grass')]

In [29]:
st.ttest_ind(df_dragon['HP'], df_grass['HP'], alternative='greater')

TtestResult(statistic=4.4991348531252635, pvalue=7.009713739308821e-06, df=143.0)

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [30]:
#code here
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [ ]:
#Step 1: Formulate the Hypotheses
#Null Hypothesis HO: The mean stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) of Legendary Pokémon are equal to those of Non-Legendary Pokémon.




#Alternative Hypothesis H1: At least one of the mean stats of Legendary Pokémon is different from those of Non-Legendary Pokémon.


#Step 2: #significance level = 0.05

In [33]:
alpha = 0.05

In [41]:
stats = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']

for stat in stats:

             df_legendary = df[df['Legendary'] == True][stat]
             df_non_legendary = df[df['Legendary'] == False][stat]

             st.f_oneway(df_legendary, df_non_legendary)      

print (st.f_oneway(df_legendary, df_non_legendary) )

F_onewayResult(statistic=95.35980155754147, pvalue=2.354075443689382e-21)

In [ ]:
# p-value very small we can regect H0.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [53]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [ ]:
# - Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.

In [55]:
school_coor = -118,34
hospital_coor = -122,37

def euclid_distance (coord1, coord2):
    return np.sqrt((coord2[0] - coord1[0]) ** 2 + (coord2[1] - coord1[1]) ** 2)


df['distance_to_school'] = df.apply(lambda row:euclid_distance((row['longitude'], row['latitude']), school_coor), axis = 1)
df['distance_to_hospital'] = df.apply(lambda row: euclid_distance((row['longitude'],row ['latitude']), hospital_coor), axis = 1)

In [46]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,distance_to_school,distance_to_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508
...,...,...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0,9.082070,4.233675
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0,9.168915,4.332320
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0,10.057614,5.358694
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0,10.026465,5.322593
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0,9.115597,4.249012

In [ ]:
# Divide your dataset into houses close and far from either a hospital or school.
# We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

In [56]:
df.dtypes

longitude               float64
latitude                float64
housing_median_age      float64
total_rooms             float64
total_bedrooms          float64
population              float64
households              float64
median_income           float64
median_house_value      float64
distance_to_school      float64
distance_to_hospital    float64
dtype: object

In [59]:
df_house_far  = df[(df['distance_to_school'] > 0.50) & (df['distance_to_hospital']> 0.50)]
df_house_close  = df[(df['distance_to_school'] < 0.50) | (df['distance_to_hospital']< 0.50)]

In [ ]:
# Choose the propper test and, with 5% significance, comment your findings

# we can comparing median_income (MI) and median_house_value (MV) depending of the distance from school or hospital

# HO: MI and MV for bouth groups have no diference
# H1: MI and MV for bouth group is diferent 

# Significance level = 0.05

In [65]:
income_test = st.ttest_ind(df_house_close['median_income'], df_house_far['median_income'])
income_test

TtestResult(statistic=17.50734256765619, pvalue=4.977653221242067e-68, df=16997.0)

In [66]:
value_test = st.ttest_ind(df_house_close['median_house_value'], df_house_far['median_house_value'])
value_test

TtestResult(statistic=38.04175343688461, pvalue=5.664850867095388e-304, df=16997.0)

In [ ]:
# P-value Significance: With a p-value of 4.977653221242067e-68, which is far below  significance level of 0.05, we reject the null hypothesis. 
# This suggests that there is statistically 
# significant evidence to declare a difference in median income between houses close to and far from schools or hospitals.

# Same for median house value - even stronger

In [69]:
income_test = st.ttest_ind(df_house_close['median_income'], df_house_far['median_income'], alternative = 'less')
income_test

TtestResult(statistic=17.50734256765619, pvalue=1.0, df=16997.0)

In [70]:
income_test = st.ttest_ind(df_house_close['median_income'], df_house_far['median_income'], alternative = 'greater')
income_test

TtestResult(statistic=17.50734256765619, pvalue=2.4888266106210336e-68, df=16997.0)