# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [2]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [3]:
df_pokemon = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df_pokemon.head()

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [4]:
df_pokemon["Type 1"].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

        * H0: mean_HP_dragon > mean_HP_grass

        * H1: mean_HP_dragon < mean_HP_grass

In [5]:
alpha = 0.05

In [6]:
df_dragon = df_pokemon[df_pokemon["Type 1"]=="Dragon"]["HP"]

In [7]:
df_grass = df_pokemon[df_pokemon["Type 1"]=="Grass"]["HP"]

In [8]:
st.ttest_ind(df_dragon, df_grass, equal_var=False)

TtestResult(statistic=3.3349632905124063, pvalue=0.0015987219490841199, df=50.83784116232685)

Since p-value is lower than alpha, we can reject H0, so mean HP for dragon pokemons aren't higher than for grass pokemons.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [9]:
leg_pokemons = df_pokemon[df_pokemon["Legendary"] == True]

non_leg_pokemons = df_pokemon[df_pokemon["Legendary"] == False]

In [10]:
leg_pokemons = leg_pokemons.dropna()
non_leg_pokemons = non_leg_pokemons.dropna()

In [11]:
leg_pokemons_numerical = leg_pokemons.select_dtypes("number").drop(columns=["Generation"])
non_leg_pokemons_numerical = non_leg_pokemons.select_dtypes("number").drop(columns=["Generation"])

        * H0: mu leg_pokemons != mu non_leg_pokemons

        * H1: mu leg_pokemons == mu non_leg_pokemons

In [12]:
alpha = 0.05

st.f_oneway(leg_pokemons_numerical, non_leg_pokemons_numerical)

F_onewayResult(statistic=array([ 64.77669922,  61.25297858,  17.14844346, 119.95390379,
        59.21425726,  42.49607572]), pvalue=array([9.06094027e-15, 4.27577495e-14, 4.19543688e-05, 1.12955816e-24,
       1.05545357e-13, 2.07395834e-10]))

According to the ANOVA results, we reject the null hypothesis, so values for legendary pokémons are not different from values for non-legendary.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [13]:
df_housing = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [14]:
def distance_school(row):
    lat_house = row["latitude"]
    lng_house = row["longitude"]
    p1 = np.array((lng_house, lat_house))
    p2 = np.array((-118, 34))
    d = np.linalg.norm(p1 - p2)
    if d < 0.5:
        return "close"
    else:
        return "far"

In [15]:
df_housing["school_distance"] = df_housing.apply(distance_school, axis=1)
df_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,school_distance
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,far

In [16]:
def distance_hospital(row):
    lat_house = row["latitude"]
    lng_house = row["longitude"]
    p1 = np.array((lng_house, lat_house))
    p2 = np.array((-122, 37))
    d = np.linalg.norm(p1 - p2)
    if d < 0.5:
        return "close"
    else:
        return "far"

In [17]:
df_housing["hospital_distance"] = df_housing.apply(distance_hospital, axis=1)
df_housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,school_distance,hospital_distance
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,far,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,far,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,far,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,far,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,far,far

In [18]:
df_housing["school_distance"].value_counts()

school_distance
far      11332
close     5668
Name: count, dtype: int64

In [19]:
houses_far = np.where((df_housing['school_distance'] == 'far') & (df_housing['hospital_distance'] == 'far'))
df_far = df_housing.loc[houses_far]

df_far.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,school_distance,hospital_distance
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,far,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,far,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,far,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,far,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,far,far

In [26]:
houses_close = np.where((df_housing['school_distance'] == 'close') | (df_housing['hospital_distance'] == 'close'))
df_close = df_housing.loc[houses_close]

df_close.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,school_distance,hospital_distance
2366,-117.51,34.00,36.0,3791.0,746.0,2258.0,672.0,3.2067,124700.0,close,far
2367,-117.51,33.97,35.0,352.0,62.0,184.0,57.0,3.6691,137500.0,close,far
2368,-117.51,33.95,12.0,9016.0,1486.0,4285.0,1457.0,4.9984,169100.0,close,far
2371,-117.52,33.99,14.0,13562.0,2057.0,7600.0,2086.0,5.2759,182900.0,close,far
2372,-117.52,33.89,2.0,17978.0,3217.0,7305.0,2463.0,5.1695,220800.0,close,far

In [27]:
df_close["school_distance"].value_counts()

school_distance
close    5668
far      1161
Name: count, dtype: int64

In [28]:
df_close["hospital_distance"].value_counts()

hospital_distance
far      5668
close    1161
Name: count, dtype: int64

        H0: df_close["median_house_value"] > df_far["median_house_value"]

        H1: df_close["median_house_value"] < df_far["median_house_value"]

In [30]:
alpha = 0.05

In [31]:
st.ttest_ind(df_close["median_house_value"], df_far["median_house_value"], equal_var=False)

TtestResult(statistic=37.992330214201516, pvalue=3.0064957768592614e-301, df=14571.229910954282)

Since the pvalue is lower than 0.05, we can reject the null hypothesis and also affirm that houses close to a hospital or a school aren't more expensive than houses far from a hospital or a school.